
import React from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { X, AlertTriangle, ArrowLeft, ExternalLink } from "lucide-react";

interface LegalDisclaimerProps {
  onClose: () => void;
}

const LegalDisclaimer: React.FC<LegalDisclaimerProps> = ({ onClose }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="w-full max-w-4xl mx-auto"
    >
      <div className="glass-card rounded-xl p-8 md:p-10 shadow-xl dark-glow">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl md:text-3xl font-serif text-resurrection-foreground text-gradient-animate flex items-center">
            <AlertTriangle className="mr-2 text-yellow-500" />
            Legal Disclaimer
          </h2>
          <Button
            variant="ghost"
            size="icon"
            onClick={onClose}
            className="rounded-full hover:bg-resurrection-primary/20"
          >
            <X className="h-5 w-5" />
          </Button>
        </div>

        <div className="space-y-6 text-resurrection-foreground/90">
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">1. Purpose and Informational Nature</h3>
            <p>Resurrection GPT is an AI-powered tool designed to facilitate personal reflection, emotional healing, and memory preservation by simulating conversations with a departed loved one based on user-provided details. This service is strictly for personal and emotional support purposes and does not claim to contact, summon, or interact with actual spirits, souls, or supernatural entities.</p>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">2. No Professional or Medical Advice</h3>
            <p>Resurrection GPT does not provide psychological counseling, medical advice, legal guidance, or religious teachings. This tool is not a substitute for therapy, professional grief counseling, or spiritual advisement. If you are experiencing severe grief, depression, or emotional distress, please seek professional mental health support or contact a licensed therapist.</p>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">3. User Responsibility & Data Accuracy</h3>
            <p>The accuracy and authenticity of responses depend entirely on the details provided by the user. Resurrection GPT does not verify historical accuracy, personal memories, or events and should not be relied upon for factual information. Users are solely responsible for the information they input and understand that conversations generated by AI are not real communications with deceased individuals.</p>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">4. Emotional & Psychological Considerations</h3>
            <p>While this service aims to provide comfort and closure, responses may evoke strong emotional reactions. By using this tool, you acknowledge that:</p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Interacting with AI-simulated personas may trigger memories, emotions, or unexpected feelings.</li>
              <li>The tool does not guarantee closure or emotional relief.</li>
              <li>You understand and accept that this experience is artificial and does not represent an actual supernatural connection.</li>
            </ul>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">5. Privacy and Confidentiality</h3>
            <p>All user inputs remain private and confidential. Resurrection GPT does not store, share, or distribute personal conversations or uploaded data beyond the current session. Users should exercise discretion when sharing sensitive or personal information.</p>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">6. Limitations & No Liability</h3>
            <p>The developers of Resurrection GPT make no claims regarding the authenticity, accuracy, or effectiveness of AI-generated interactions. By using this service, you acknowledge that all AI-generated conversations are fictional and should be treated as such. The creators of this tool shall not be held liable for any emotional, psychological, or personal consequences resulting from its use.</p>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">7. Age Requirement</h3>
            <p>This tool is intended for users 18 years and older. If you are under 18, you may only use Resurrection GPT with parental or guardian consent.</p>
          </div>
          
          <div>
            <h3 className="font-medium text-resurrection-primary text-lg mb-2">8. Agreement to Terms</h3>
            <p>By using Resurrection GPT, you acknowledge and agree to the terms outlined in this disclaimer. If you do not agree with these terms, please discontinue use immediately.</p>
          </div>
        </div>

        <div className="mt-8 flex justify-between items-center">
          <Button 
            variant="outline" 
            onClick={onClose}
            className="border-resurrection-primary/30 text-resurrection-primary hover:bg-resurrection-primary/10 flex items-center"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
          
          <a 
            href="https://chatgpt.com/g/g-KrXujWZPM-talk-to-your-god-gpt" 
            target="_blank" 
            rel="noopener noreferrer"
          >
            <Button 
              className="bg-resurrection-primary hover:bg-resurrection-primary/80 text-white"
            >
              Begin Your Divine Connection
              <ExternalLink className="ml-2 h-4 w-4" />
            </Button>
          </a>
        </div>
      </div>
    </motion.div>
  );
};

export default LegalDisclaimer;
