import React from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { X, AlertTriangle, ArrowLeft, ExternalLink, Shield, Info } from "lucide-react";

interface LegalDisclaimerProps {
  onClose: () => void;
}

const LegalDisclaimer: React.FC<LegalDisclaimerProps> = ({ onClose }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="w-full max-w-4xl mx-auto"
    >
      <div className="glass-card rounded-xl p-8 md:p-10 shadow-xl dark-glow">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl md:text-3xl font-serif text-resurrection-foreground text-gradient-animate flex items-center">
            <Shield className="mr-2 text-yellow-500" />
            Educational & Legal Disclaimer
          </h2>
          <Button
            variant="ghost"
            size="icon"
            onClick={onClose}
            className="rounded-full hover:bg-resurrection-primary/20"
          >
            <X className="h-5 w-5" />
          </Button>
        </div>

        <div className="space-y-6 text-resurrection-foreground/90">
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              1. Purpose and Educational Nature
            </h3>
            <p className="leading-relaxed">
              Talk to the Gods GPT is an AI-powered educational tool designed for religious studies, academic research, and exploration of theological concepts through simulated conversations based on user-selected religious traditions. This service is strictly for informational, educational, and research purposes only. It does not claim to represent actual religious authorities or divine entities.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              2. No Religious Authority or Theological Guidance
            </h3>
            <p className="leading-relaxed">
              Talk to the Gods GPT does not provide official religious counsel, theological interpretation, or authoritative spiritual guidance. This tool is not endorsed by or affiliated with any religious organization. It is not a substitute for proper religious education, consultation with qualified religious leaders, or study of recognized sacred texts. If you seek authentic religious guidance, please consult with recognized religious authorities in your tradition.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              3. AI Simulation & Academic Interpretation
            </h3>
            <p className="leading-relaxed">
              The responses generated by Talk to the Gods GPT are based on AI interpretation of religious texts, scholarly works, theological teachings, and historical accounts of various religious traditions. The accuracy, authenticity, and appropriateness of responses are limited by available information and AI capabilities. Users should understand that all responses are computational interpretations for educational purposes, not authoritative religious pronouncements.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              4. Respect for Religious Traditions
            </h3>
            <p className="leading-relaxed">
              While Talk to the Gods GPT strives to represent religious traditions respectfully and accurately, users acknowledge that:
            </p>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>Different interpretations of religious concepts exist across traditions, sects, and historical periods</li>
              <li>Some religious traditions may consider AI simulation inappropriate or insufficient for understanding their beliefs</li>
              <li>The tool is intended for respectful academic exploration, not mockery or trivializing of religious beliefs</li>
              <li>Users should approach interactions with appropriate respect for the religious and cultural significance of the traditions they explore</li>
            </ul>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              5. Privacy and Confidentiality
            </h3>
            <p className="leading-relaxed">
              All user inputs remain private and confidential. Talk to the Gods GPT does not store, share, or distribute personal conversations or uploaded data beyond the current session. Users should exercise discretion when sharing sensitive personal information.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              6. User Responsibility
            </h3>
            <p className="leading-relaxed">
              By using Talk to the Gods GPT, users agree to:
            </p>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>Use the tool for educational and research purposes</li>
              <li>Exercise critical thinking and academic rigor regarding all AI-generated responses</li>
              <li>Not use the tool to promote hate, discrimination, or religious intolerance</li>
              <li>Not attribute or represent the AI-generated content as authentic communications from religious authorities</li>
              <li>Respect the religious and cultural significance of the traditions represented</li>
            </ul>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              7. Limitations & No Liability
            </h3>
            <p className="leading-relaxed">
              The developers of Talk to the Gods GPT make no claims regarding the theological accuracy, religious authenticity, or doctrinal correctness of AI-generated interactions. By using this service, you acknowledge that all AI-generated conversations are educational simulations and should be treated as such. The creators of this tool shall not be held liable for any theological, academic, emotional, psychological, or personal consequences resulting from its use.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              8. Age Requirement
            </h3>
            <p className="leading-relaxed">
              This tool is intended for users 18 years and older. If you are under 18, you may only use Talk to the Gods GPT with parental or guardian consent.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-yellow-50/10">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <AlertTriangle className="h-5 w-5 mr-2 text-yellow-500" />
              9. Agreement to Terms
            </h3>
            <p className="leading-relaxed">
              By using Talk to the Gods GPT, you acknowledge and agree to the terms outlined in this disclaimer. For complete terms and conditions, please visit our <a href="https://aiwebtools.lovable.app/disclaimers" target="_blank" rel="noopener noreferrer" className="text-resurrection-primary hover:underline">Terms of Service</a>. If you do not agree with these terms, please discontinue use immediately.
            </p>
          </div>
        </div>

        <div className="mt-10 flex justify-between items-center">
          <Button 
            variant="outline" 
            onClick={onClose}
            className="border-resurrection-primary/30 text-resurrection-primary hover:bg-resurrection-primary/10 flex items-center"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
          
          <a 
            href="https://chatgpt.com/g/g-KrXujWZPM-talk-to-your-god-gpt" 
            target="_blank" 
            rel="noopener noreferrer"
          >
            <Button 
              className="bg-resurrection-primary hover:bg-resurrection-primary/80 text-white"
            >
              Begin Religious Studies
              <ExternalLink className="ml-2 h-4 w-4" />
            </Button>
          </a>
        </div>
      </div>
    </motion.div>
  );
};

export default LegalDisclaimer;
