
import React from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { X, AlertTriangle, ArrowLeft, ExternalLink, Shield, Info } from "lucide-react";

interface LegalDisclaimerProps {
  onClose: () => void;
}

const LegalDisclaimer: React.FC<LegalDisclaimerProps> = ({ onClose }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="w-full max-w-4xl mx-auto"
    >
      <div className="glass-card rounded-xl p-8 md:p-10 shadow-xl dark-glow">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl md:text-3xl font-serif text-resurrection-foreground text-gradient-animate flex items-center">
            <Shield className="mr-2 text-yellow-500" />
            Legal & Spiritual Disclaimer
          </h2>
          <Button
            variant="ghost"
            size="icon"
            onClick={onClose}
            className="rounded-full hover:bg-resurrection-primary/20"
          >
            <X className="h-5 w-5" />
          </Button>
        </div>

        <div className="space-y-6 text-resurrection-foreground/90">
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              1. Purpose and Spiritual Nature
            </h3>
            <p className="leading-relaxed">
              Talk to the Gods GPT is an AI-powered tool designed to facilitate spiritual reflection, contemplation, and exploration of divine wisdom through simulated conversations with deities and spiritual figures based on user-selected preferences. This service is strictly for personal spiritual growth, emotional support, and educational purposes. It does not claim to contact, summon, or interact with actual divine beings, spirits, or supernatural entities.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              2. No Religious Authority or Theological Guidance
            </h3>
            <p className="leading-relaxed">
              Talk to the Gods GPT does not provide official religious counsel, theological interpretation, or authoritative spiritual guidance. This tool is not endorsed by or affiliated with any religious organization. It is not a substitute for proper religious education, consultation with qualified religious leaders, or study of recognized sacred texts. If you seek authentic religious guidance, please consult with recognized religious authorities in your tradition.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              3. AI Simulation & Interpretation
            </h3>
            <p className="leading-relaxed">
              The responses generated by Talk to the Gods GPT are based on AI interpretation of religious texts, spiritual teachings, mythological accounts, and cultural understandings of various deities and spiritual figures. The accuracy, authenticity, and appropriateness of responses are limited by available information and AI capabilities. Users should understand that all responses are computational interpretations, not divine revelations or authentic divine communication.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              4. Respect for Religious Traditions
            </h3>
            <p className="leading-relaxed">
              While Talk to the Gods GPT strives to represent deities and spiritual figures respectfully and authentically, users acknowledge that:
            </p>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>Different interpretations of deities exist across traditions, sects, and historical periods</li>
              <li>Some religious traditions may consider AI simulation of deities inappropriate or disrespectful</li>
              <li>The tool is intended for respectful spiritual exploration, not mockery or trivializing of religious beliefs</li>
              <li>Users should approach interactions with appropriate reverence for the religious and cultural significance of the deities they choose to engage with</li>
            </ul>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              5. Privacy and Confidentiality
            </h3>
            <p className="leading-relaxed">
              All user inputs remain private and confidential. Talk to the Gods GPT does not store, share, or distribute personal conversations or uploaded data beyond the current session. Users should exercise discretion when sharing sensitive personal or spiritual information.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              6. User Responsibility
            </h3>
            <p className="leading-relaxed">
              By using Talk to the Gods GPT, users agree to:
            </p>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>Use the tool for personal spiritual exploration and not as a source of authoritative religious guidance</li>
              <li>Exercise critical thinking and personal discernment regarding all AI-generated responses</li>
              <li>Not use the tool to promote hate, discrimination, or religious intolerance</li>
              <li>Not attribute or represent the AI-generated content as authentic communications from actual divine entities</li>
              <li>Respect the religious and cultural significance of the spiritual figures represented</li>
            </ul>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              7. Limitations & No Liability
            </h3>
            <p className="leading-relaxed">
              The developers of Talk to the Gods GPT make no claims regarding the theological accuracy, spiritual authenticity, or religious correctness of AI-generated interactions. By using this service, you acknowledge that all AI-generated conversations are interpretive simulations and should be treated as such. The creators of this tool shall not be held liable for any spiritual, theological, emotional, psychological, or personal consequences resulting from its use.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-muted/30">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <Info className="h-5 w-5 mr-2 text-resurrection-accent" />
              8. Age Requirement
            </h3>
            <p className="leading-relaxed">
              This tool is intended for users 18 years and older. If you are under 18, you may only use Talk to the Gods GPT with parental or guardian consent.
            </p>
          </div>
          
          <div className="p-4 border border-resurrection-primary/20 rounded-lg bg-yellow-50/10">
            <h3 className="font-medium text-resurrection-primary text-lg mb-3 flex items-center">
              <AlertTriangle className="h-5 w-5 mr-2 text-yellow-500" />
              9. Agreement to Terms
            </h3>
            <p className="leading-relaxed">
              By using Talk to the Gods GPT, you acknowledge and agree to the terms outlined in this disclaimer. If you do not agree with these terms, please discontinue use immediately.
            </p>
          </div>
        </div>

        <div className="mt-10 flex justify-between items-center">
          <Button 
            variant="outline" 
            onClick={onClose}
            className="border-resurrection-primary/30 text-resurrection-primary hover:bg-resurrection-primary/10 flex items-center"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
          
          <a 
            href="https://chatgpt.com/g/g-KrXujWZPM-talk-to-your-god-gpt" 
            target="_blank" 
            rel="noopener noreferrer"
          >
            <Button 
              className="bg-resurrection-primary hover:bg-resurrection-primary/80 text-white"
            >
              Begin Your Divine Connection
              <ExternalLink className="ml-2 h-4 w-4" />
            </Button>
          </a>
        </div>
      </div>
    </motion.div>
  );
};

export default LegalDisclaimer;
